#!/usr/bin/env bash
# main.sh - one-command setup + service manager for OpenThai-SystemOne
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVICE="${SERVICE:-openthai-systemone}"
VENV="$APP_DIR/.venv"
PY="$VENV/bin/python"
SERVE="$APP_DIR/serve.py"
PKG="openthai-systemone[server] @ git+https://github.com/iapp-technology/openthai-systemone"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-8000}"
MODEL="${OPENTHAI_SYSTEMONE_MODEL:-iapp/OpenThai-SystemOne}"
HF_HOME_DIR="${HF_HOME:-$HOME/.cache/huggingface}"
MODE="${MODE:-system}"
WORKERS="${WORKERS:-1}"
BASE="http://127.0.0.1:$PORT"

if [[ "$MODE" == "user" ]]; then
  UNIT_DIR="$HOME/.config/systemd/user"; WANTED_BY="default.target"
else
  UNIT_DIR="/etc/systemd/system";        WANTED_BY="multi-user.target"
fi
UNIT="$UNIT_DIR/$SERVICE.service"
OVERRIDE_DIR="$UNIT_DIR/$SERVICE.service.d"

c_ok()   { printf '  \033[32mOK\033[0m   %s\n' "$*"; }
c_bad()  { printf '  \033[31mERR\033[0m  %s\n' "$*"; }
c_warn() { printf '  \033[33mWARN\033[0m %s\n' "$*"; }
step()   { printf '\n==> %s\n' "$*"; }
die()    { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

sc()  { if [[ "$MODE" == "user" ]]; then systemctl --user "$@"; else sudo systemctl "$@"; fi; }
jrn() { if [[ "$MODE" == "user" ]]; then journalctl --user -u "$SERVICE" "$@"; else sudo journalctl -u "$SERVICE" "$@"; fi; }
as_root() { if [[ "$(id -u)" -eq 0 ]]; then "$@"; else sudo "$@"; fi; }

# ---------------------------------------------------------------- bootstrap
fix_broken_apt() {
  local removed=0 f
  shopt -s nullglob
  for f in /etc/apt/sources.list.d/*ookla* /etc/apt/sources.list.d/*speedtest*; do
    if as_root rm -f "$f"; then removed=1; fi
  done
  shopt -u nullglob
  if [[ "$removed" -eq 1 ]]; then c_ok "removed broken speedtest apt source"; fi
}

apt_install() {
  fix_broken_apt
  as_root apt-get update -qq || c_warn "apt-get update had errors, continuing"
  as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y "$@"
}

ensure_uv() {
  command -v uv >/dev/null 2>&1 || die "uv not found: curl -LsSf https://astral.sh/uv/install.sh | sh"
  c_ok "uv $(uv --version | awk '{print $2}')"
}

ensure_compiler() {
  if command -v gcc >/dev/null 2>&1; then
    c_ok "gcc: $(command -v gcc)"
  else
    c_warn "gcc missing, installing build-essential"
    apt_install build-essential || die "could not install build-essential"
    c_ok "gcc installed"
  fi
}

ensure_venv() {
  if [[ -x "$PY" ]]; then
    c_ok "venv: $VENV"
  else
    c_warn "creating venv (python 3.12)"
    uv venv --python 3.12 --allow-existing "$VENV"
    c_ok "venv created"
  fi
}

ensure_package() {
  if "$PY" -c 'import openthai_systemone' >/dev/null 2>&1; then
    c_ok "openthai-systemone installed"
  else
    c_warn "installing package (first run downloads torch, ~3GB)"
    uv pip install --python "$PY" "$PKG"
    c_ok "package installed"
  fi
}

ensure_headers() {
  local inc
  inc="$("$PY" -c 'import sysconfig; print(sysconfig.get_paths()["include"])')"
  if [[ -f "$inc/Python.h" ]]; then
    c_ok "Python.h: $inc/Python.h"
    return 0
  fi
  c_warn "Python.h missing ($inc), installing python3.12-dev"
  apt_install python3.12-dev || die "could not install python3.12-dev"
  [[ -f "$inc/Python.h" ]] || die "Python.h still missing after install"
  c_ok "Python.h installed"
}

check_cuda() {
  "$PY" - <<'PY'
import torch
print(f"  torch {torch.__version__} | cuda build {torch.version.cuda}")
if torch.cuda.is_available():
    print(f"  OK   GPU: {torch.cuda.get_device_name(0)}")
else:
    print("  WARN CUDA unavailable - will run on CPU (much slower)")
PY
}

serve_py_write() {
  cat > "$SERVE" <<'PY'
#!/usr/bin/env python
"""Preload OpenThai-SystemOne, then serve it.

Started instead of `uvicorn ...` so the weights are loaded AND the Triton kernels
are compiled before the socket opens. Without this, the first POST pays ~60s of
weight loading plus the kernel compile, and every restart pays it again.

Generated by main.sh - edits here are overwritten on `main.sh install`.
"""
import os
import time

HOST = os.environ.get("HOST", "0.0.0.0")
PORT = int(os.environ.get("PORT", "8000"))
MODEL = os.environ.get("OPENTHAI_SYSTEMONE_MODEL", "iapp/OpenThai-SystemOne")


def preload() -> None:
    from openthai_systemone.server import get_client

    t0 = time.perf_counter()
    print(f"[serve] loading {MODEL} ...", flush=True)
    client = get_client()
    print(f"[serve] weights ready in {time.perf_counter() - t0:.1f}s", flush=True)

    # One dummy decision forces the Gated-DeltaNet / RoPE Triton kernels to
    # compile now instead of on the first real request.
    t1 = time.perf_counter()
    client.system_one("warmup", {"q": {"type": "noul", "instructions": "Is this a test?"}})
    print(f"[serve] kernels compiled in {time.perf_counter() - t1:.1f}s", flush=True)


def main() -> None:
    preload()

    import uvicorn
    from openthai_systemone.server import app

    print(f"[serve] listening on {HOST}:{PORT}", flush=True)
    # workers=1 on purpose: the preloaded client lives in this process, and each
    # extra worker would load its own copy of the model onto the GPU.
    uvicorn.run(app, host=HOST, port=PORT, workers=1)


if __name__ == "__main__":
    main()
PY
  chmod +x "$SERVE"
  c_ok "serve.py (preload wrapper)"
}

unit_write() {
  local tmp exec_line
  if [[ "$WORKERS" -gt 1 ]]; then
    exec_line="$PY -m uvicorn openthai_systemone.server:app --host $HOST --port $PORT --workers $WORKERS"
  else
    exec_line="$PY $SERVE"
  fi

  tmp="$(mktemp)"
  {
    echo "[Unit]"
    echo "Description=OpenThai-SystemOne decision model server"
    echo "After=network-online.target"
    echo "Wants=network-online.target"
    echo
    echo "[Service]"
    echo "Type=simple"
    if [[ "$MODE" == "system" ]]; then echo "User=$USER"; fi
    echo "WorkingDirectory=$APP_DIR"
    echo "Environment=OPENTHAI_SYSTEMONE_MODEL=$MODEL"
    echo "Environment=HF_HOME=$HF_HOME_DIR"
    echo "Environment=HOST=$HOST"
    echo "Environment=PORT=$PORT"
    echo "Environment=CC=/usr/bin/gcc"
    echo "Environment=PYTHONUNBUFFERED=1"
    echo "Environment=PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"
    echo "ExecStart=$exec_line"
    echo "Restart=always"
    echo "RestartSec=5"
    echo "TimeoutStopSec=20"
    echo
    echo "[Install]"
    echo "WantedBy=$WANTED_BY"
  } > "$tmp"

  if [[ "$MODE" == "user" ]]; then
    mkdir -p "$UNIT_DIR"; install -m 0644 "$tmp" "$UNIT"
  else
    sudo mkdir -p "$UNIT_DIR"; sudo install -m 0644 "$tmp" "$UNIT"
  fi
  rm -f "$tmp"
  c_ok "unit: $UNIT (workers=$WORKERS)"
}

wait_ready() {
  local i
  for i in $(seq 1 90); do
    if curl -sf -m 2 "$BASE/healthz" >/dev/null 2>&1; then return 0; fi
    sleep 1
  done
  return 1
}

# ---------------------------------------------------------------- commands
cmd_install() {
  step "1/7 system dependencies"; ensure_uv; ensure_compiler
  step "2/7 python environment";  ensure_venv
  step "3/7 packages";            ensure_package
  step "4/7 python headers";      ensure_headers
  step "5/7 gpu";                 check_cuda
  step "6/7 service files";       serve_py_write; unit_write
  step "7/7 service"
  sc daemon-reload
  sc enable "$SERVICE"
  sc restart "$SERVICE"
  c_ok "service enabled + started"
  cmd_warm || c_warn "warm-up failed - run: $0 doctor"
  step "done"
  c_ok "endpoint: http://$HOST:$PORT/v1/systemone"
  c_ok "manage with: $0 {status|bench|logs|restart|stop|doctor}"
}

cmd_uninstall() {
  sc disable --now "$SERVICE" 2>/dev/null || true
  if [[ -d "$OVERRIDE_DIR" ]]; then
    if [[ "$MODE" == "user" ]]; then rm -rf "$OVERRIDE_DIR"; else sudo rm -rf "$OVERRIDE_DIR"; fi
    c_ok "removed override dir"
  fi
  if [[ -f "$UNIT" ]]; then
    if [[ "$MODE" == "user" ]]; then rm -f "$UNIT"; else sudo rm -f "$UNIT"; fi
    c_ok "removed unit"
  fi
  sc daemon-reload 2>/dev/null || true
  c_ok "uninstalled"
}

cmd_health() {
  local out
  if out="$(curl -s -m 5 "$BASE/healthz")"; then c_ok "$BASE/healthz -> $out"
  else c_bad "$BASE/healthz unreachable"; fi
}

cmd_warm() {
  step "waiting for service (preload happens before the socket opens)"
  if ! wait_ready; then
    c_bad "no /healthz at $BASE after 90s"
    jrn -n 30 --no-pager 2>/dev/null | tail -30 || true
    return 1
  fi
  c_ok "service up"

  local out
  if out="$(curl -s -m 900 -X POST "$BASE/v1/systemone" \
      -H 'content-type: application/json' \
      -d '{"state":"warmup","questions":{"q":{"type":"noul","instructions":"Is this a test?"}}}')"; then
    if printf '%s' "$out" | grep -q '"noul"'; then
      c_ok "model ready: $out"
    else
      c_bad "unexpected response: $out"
      return 1
    fi
  else
    c_bad "no response from $BASE"
    return 1
  fi
}

cmd_bench() {
  local n="${1:-20}"
  step "benchmark: $n sequential noul calls"
  local i
  for i in $(seq 1 "$n"); do
    curl -s -o /dev/null -m 120 -w '%{time_total}\n' -X POST "$BASE/v1/systemone" \
      -H 'content-type: application/json' \
      -d '{"state":{"ticket":"โดนหักเงินซ้ำสองครั้ง ขอเงินคืนด่วน"},"questions":{"refund":{"type":"noul","instructions":"ลูกค้าขอเงินคืนอย่างชัดเจนหรือไม่"}}}'
  done | sort -n | awk '
    { a[NR] = $1 * 1000 }
    END {
      if (NR == 0) { print "  (no samples)"; exit }
      printf "  min  %6.0f ms\n", a[1]
      printf "  p50  %6.0f ms\n", a[int(NR * 0.50) < 1 ? 1 : int(NR * 0.50)]
      printf "  p95  %6.0f ms\n", a[int(NR * 0.95) < 1 ? 1 : int(NR * 0.95)]
      printf "  max  %6.0f ms\n", a[NR]
    }'
}

cmd_status() {
  sc status "$SERVICE" --no-pager 2>/dev/null || true
  echo
  cmd_health
}

cmd_logs() {
  local n="${1:-100}" follow="${2:-f}"
  if [[ "$follow" == "f" ]]; then jrn -n "$n" -f; else jrn -n "$n" --no-pager; fi
}

cmd_gpu() { "$PY" - <<'PY'
import torch
print("torch     ", torch.__version__)
print("cuda build", torch.version.cuda)
print("available ", torch.cuda.is_available())
if torch.cuda.is_available():
    print("device    ", torch.cuda.get_device_name(0))
PY
}

cmd_config() {
  cat <<EOF
APP_DIR    $APP_DIR
venv       $VENV
serve      $SERVE
unit       $UNIT
mode       $MODE
workers    $WORKERS
bind       $HOST:$PORT
model      $MODEL
HF_HOME    $HF_HOME_DIR
EOF
}

cmd_doctor() {
  local fail=0 inc
  step "doctor"
  if [[ -x "$PY" ]]; then c_ok "venv python: $PY"; else c_bad "venv python missing"; fail=1; fi
  if "$PY" -c 'import openthai_systemone' 2>/dev/null; then c_ok "openthai_systemone importable"; else c_bad "openthai_systemone not importable"; fail=1; fi
  if command -v gcc >/dev/null 2>&1; then c_ok "gcc: $(command -v gcc)"; else c_bad "gcc missing (apt-get install build-essential)"; fail=1; fi
  inc="$("$PY" -c 'import sysconfig; print(sysconfig.get_paths()["include"])' 2>/dev/null || true)"
  if [[ -n "$inc" && -f "$inc/Python.h" ]]; then c_ok "Python.h: $inc/Python.h"; else c_bad "Python.h missing (apt-get install python3.12-dev)"; fail=1; fi
  if [[ -f "$SERVE" ]]; then c_ok "serve.py present (preload enabled)"; else c_warn "serve.py missing - first request will be slow; run: $0 install"; fi
  if "$PY" -c 'import torch,sys; sys.exit(0 if torch.cuda.is_available() else 1)' 2>/dev/null; then c_ok "CUDA available"; else c_warn "CUDA unavailable - CPU fallback"; fi
  if curl -sf -m 3 "$BASE/healthz" >/dev/null 2>&1; then c_ok "service healthy at $BASE"; else c_bad "no /healthz at $BASE"; fail=1; fi
  if [[ -f "$UNIT" ]]; then c_ok "unit: $UNIT"; else c_bad "unit missing - run: $0 install"; fail=1; fi
  if [[ -d "$OVERRIDE_DIR" ]]; then
    c_warn "override dir shadows the unit:"
    ls -1 "$OVERRIDE_DIR" | sed 's/^/       /'
  fi
  if sc is-enabled "$SERVICE" >/dev/null 2>&1; then c_ok "enabled at boot"; else c_warn "not enabled at boot"; fi
  echo
  step "last journal errors"
  jrn -n 200 --no-pager 2>/dev/null | grep -iE 'error|exception|traceback' | tail -5 || echo "  (none)"
  echo
  if [[ "$fail" -eq 0 ]]; then c_ok "no blocking problems"; else c_bad "problems found"; fi
}

cmd_run() {
  HOST="$HOST" PORT="$PORT" OPENTHAI_SYSTEMONE_MODEL="$MODEL" exec "$PY" "$SERVE"
}

usage() {
  cat <<EOF
usage: $0 <command>

  install      full setup: deps + venv + packages + headers + service + warm
  uninstall    stop, disable, remove unit and any override
  enable       install + enable at boot
  disable      disable at boot + stop
  start stop restart reload
  status       service state + /healthz
  bench [n]    latency percentiles (default 20 calls)
  logs [n] [f] journal (default last 100, 'f' to follow)
  health       curl /healthz
  warm         wait for readiness, then one request
  doctor       diagnose venv/gcc/Python.h/serve.py/CUDA/unit/port
  gpu          torch + CUDA report
  config       show effective settings
  run          foreground with preload (debugging)

env overrides: HOST PORT MODEL HF_HOME SERVICE WORKERS MODE=system|user

  WORKERS=1 (default) uses serve.py: model preloaded, first request already fast.
  WORKERS>1  uses plain uvicorn: parallel, but each worker loads its own model copy.
EOF
}

case "${1:-help}" in
  install)    cmd_install ;;
  uninstall)  cmd_uninstall ;;
  enable)     cmd_install ;;
  disable)    sc disable --now "$SERVICE" 2>/dev/null || true ;;
  start)      sc start "$SERVICE" ;;
  stop)       sc stop "$SERVICE" ;;
  restart)    sc restart "$SERVICE" ;;
  reload)     sc restart "$SERVICE" ;;
  status)     cmd_status ;;
  bench)      shift; cmd_bench "${1:-20}" ;;
  logs)       shift; cmd_logs "${1:-100}" "${2:-f}" ;;
  health)     cmd_health ;;
  warm)       cmd_warm ;;
  doctor)     cmd_doctor ;;
  gpu)        cmd_gpu ;;
  config)     cmd_config ;;
  run)        cmd_run ;;
  help|*)     usage ;;
esac
