#!/usr/bin/env python
"""Preload OpenThai-SystemOne, then serve it.

Started instead of `uvicorn ...` so the weights are loaded AND the Triton kernels
are compiled before the socket opens. Without this, the first POST pays ~60s of
weight loading plus the kernel compile, and every restart pays it again.

Generated by main.sh - edits here are overwritten on `main.sh install`.
"""
import os
import time

HOST = os.environ.get("HOST", "0.0.0.0")
PORT = int(os.environ.get("PORT", "8000"))
MODEL = os.environ.get("OPENTHAI_SYSTEMONE_MODEL", "iapp/OpenThai-SystemOne")


def preload() -> None:
    from openthai_systemone.server import get_client

    t0 = time.perf_counter()
    print(f"[serve] loading {MODEL} ...", flush=True)
    client = get_client()
    print(f"[serve] weights ready in {time.perf_counter() - t0:.1f}s", flush=True)

    # One dummy decision forces the Gated-DeltaNet / RoPE Triton kernels to
    # compile now instead of on the first real request.
    t1 = time.perf_counter()
    client.system_one("warmup", {"q": {"type": "noul", "instructions": "Is this a test?"}})
    print(f"[serve] kernels compiled in {time.perf_counter() - t1:.1f}s", flush=True)


def main() -> None:
    preload()

    import uvicorn
    from openthai_systemone.server import app

    print(f"[serve] listening on {HOST}:{PORT}", flush=True)
    # workers=1 on purpose: the preloaded client lives in this process, and each
    # extra worker would load its own copy of the model onto the GPU.
    uvicorn.run(app, host=HOST, port=PORT, workers=1)


if __name__ == "__main__":
    main()
